use crate::ast::Node;

pub fn emit_c(program: &[Node]) -> String {
    let mut out = String::new();

    out.push_str(C_HEADER);
    out.push_str("int main(void) {\n");

    emit_block(&mut out, program, 1);

    out.push_str("  return 0;\n}\n");
    out
}

fn emit_block(out: &mut String, nodes: &[Node], indent: usize) {
    for node in nodes {
        emit_node(out, node, indent);
    }
}

fn emit_node(out: &mut String, node: &Node, indent: usize) {
    let pad = "  ".repeat(indent);

    match node {
        Node::Add(delta) => {
            out.push_str(&format!("{pad}add_cell({});\n", c_int(*delta)));
        }

        Node::Move(delta) => {
            out.push_str(&format!("{pad}move_ptr({});\n", c_int(*delta)));
        }

        Node::Put => {
            out.push_str(&format!("{pad}put_cell();\n"));
        }

        Node::Get => {
            out.push_str(&format!("{pad}get_cell();\n"));
        }

        Node::Clear => {
            out.push_str(&format!("{pad}set_cell(0);\n"));
        }

        Node::Transfer { offset, multiplier } => {
            out.push_str(&format!(
                "{pad}transfer({}, {});\n",
                c_int(*offset),
                c_int(*multiplier)
            ));
        }

        Node::Loop(body) => {
            out.push_str(&format!("{pad}while (current_cell()) {{\n"));
            emit_block(out, body, indent + 1);
            out.push_str(&format!("{pad}}}\n"));
        }
    }
}

fn c_int(value: i64) -> String {
    if value == i64::MIN {
        "(-9223372036854775807LL - 1)".to_string()
    } else {
        format!("{value}LL")
    }
}

const C_HEADER: &str = r##"/* Generated by brainmelt. */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef TAPE_SIZE
#define TAPE_SIZE 30000
#endif

static uint8_t tape[TAPE_SIZE];
static size_t ptr = 0;

static inline void check_current(void) {
#ifndef BF_NO_BOUNDS
    if (ptr >= TAPE_SIZE) {
        fprintf(stderr, "brainmelt runtime: tape index out of bounds\n");
        exit(1);
    }
#endif
}

static inline uint8_t current_cell(void) {
    check_current();
    return tape[ptr];
}

static inline void set_cell(uint8_t value) {
    check_current();
    tape[ptr] = value;
}

static inline void add_cell(long long delta) {
    check_current();
    tape[ptr] = (uint8_t)(tape[ptr] + (uint8_t)delta);
}

static inline void move_ptr(long long delta) {
#ifndef BF_NO_BOUNDS
    long long next = (long long)ptr + delta;
    if (next < 0 || next >= (long long)TAPE_SIZE) {
        fprintf(stderr, "brainmelt runtime: tape index out of bounds\n");
        exit(1);
    }
    ptr = (size_t)next;
#else
    ptr = (size_t)((long long)ptr + delta);
#endif
}

static inline void put_cell(void) {
    putchar((int)current_cell());
}

static inline void get_cell(void) {
    check_current();
    fflush(stdout);
    int c = getchar();
    tape[ptr] = (c == EOF ? 0 : (uint8_t)c);
}

static inline void transfer(long long offset, long long multiplier) {
    check_current();

    uint8_t value = tape[ptr];
    tape[ptr] = 0;

    if (value == 0 || multiplier == 0) {
        return;
    }

    long long target = (long long)ptr + offset;

#ifndef BF_NO_BOUNDS
    if (target < 0 || target >= (long long)TAPE_SIZE) {
        fprintf(stderr, "brainmelt runtime: tape index out of bounds\n");
        exit(1);
    }
#endif

    size_t target_ptr = (size_t)target;
    uint8_t delta = (uint8_t)((uint8_t)multiplier * value);
    tape[target_ptr] = (uint8_t)(tape[target_ptr] + delta);
}

"##;
